config/routes.rb
InternDB::Application.routes.draw do

  resources :users
  resources :experiences
  match '/experiences/company/:id' => "experiences#company", :via => :get

  root to: 'users#home'
  root :to => redirect('/experiences')

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/:provider', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy'
  match '/admin', :to => 'admin#home'
  match '/admin/denied'
  match '/admin/unapproved'
  match '/admin/:id/approve' => 'admin#approve'
  match '/admin/:id/deny' => 'admin#deny'
  resources :admin

end

app/views/admin/denied.html.haml
%h1 Colgate InternDB Denied Posts


%table#experiences
  %thead
    %tr
      %th Student
      %th Company
      %th Industry
      %th Role
      %th Date of Internship
      %th Date of Review
      %th Composite
      %th View
  %tbody
    - @denied.each do |ex|
      %tr
        %td= ex.get_name
        %td= ex.organization
        %td= ex.industry
        %td= ex.function
        %td= ex.date_str
        %td= ex.updated_at
        %td= ex.composite.round(2)
        %td= link_to "View", "/admin/#{ex.id}"

=link_to 'Home', '/'

app/views/admin/edit.html.haml
%h1 Edit Experience!

= form_tag "/admin/#{@experience.id}", :method => :put do 
   = label :experience, :organization, 'Name of Organization'  
   = text_field :experience, 'organization'
   %br
   = label :experience, :city, "City"
   = text_field :experience, 'city'
   = label :experience, :state, "State"
   = text_field :experience, 'state'
   = label :experience, :country, "Country"
   = text_field :experience, 'country'
   %br
   %br
   = label :experience, :industry, "Industry"
   = select :experience, :industry, ['The Arts/Design', "Business Services", "Communications/Media", "Consulting", "Computing/Technology", "Education", "Entertainment/Film/TV", "Environment/Energy", "Financial Services", "Government/Public Service", "Healthcare", "Law/Legal", "Non-profit/Advocacy", "Sports/Leisure", "Scientific Reasearch"]
   = label :experience, :function, "In what department?"
   = text_field :experience, 'function'
   %br
   = label :experience, :season, "Season"
   = select :experience, :year, [2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030] 
   = label :experience, :season, "Season"
   = select :experience, :season, ['Spring', 'Winter','Summer','Fall']
   %br
   = label :experience, "Paid?"
   = select :experience, :paid, ['Yes','No']
   %br
   = label :experience, :hands_on_review, 'Briefly describe the type of work that you did and/or any projects you worked on:'
   %br
   = text_area :experience, 'hands_on_review'
   %br
   = label :experience, :hands_on_rating, 'Please rate how relevant the work you did was to your industry (1 for being a coffee monkey, 5 for crucial work)'
   %br
   =select :experience, :hands_on_rating, ['1','2','3','4','5']
   %br
   = label :experience, :network_review, 'Briefly describe the networking oppurtinities your experience gave you:'
   %br
   = text_area :experience, 'network_review'
   %br
   = label :experience, :network_rating, 'Please rate the networking you obtained during your experience (1 for no networking, 5 for a spiderweb\'s worth)'
   %br
   =select :experience, :network_rating, ['1','2','3','4','5']
   %br
   = label :experience, :exposure_review, 'Briefely describe how the company exposed you to the industry through presentations, speakers, and day to day work:'
   %br
   = text_area :experience, 'exposure_review'
   %br
   = label :experience, :exposure_rating, 'Please the exposure to your industry during your experience (1 being terrible, 5 being great)'
   %br
   =select :experience, :exposure_rating, ['1','2','3','4','5']
   %br
   = label :experience, :contact, "Can you please name a contact that aided you in securing this experience?"
   = text_field :experience, :contact
   %br
   = label :experience, :contact_relation, "What is the contact's relation to Colgate?"
   = select :experience, :contact_relation, ['Parent', 'Alumni', 'Faculty', 'Other/None']
   %br
   = label :experience, "Knowing what you know now, would you repeat the experience?"
   = select :experience, :repeat, ['Yes', 'No']
   %br
   = label :experience, :comments, "Any additional comments?"
   %br
   = text_area :experience, 'comments'
   %br
   = submit_tag "Submit" 

=button_to 'Cancel', "/admin/#{@experience.id}"

app/views/admin/home.html.haml
%h1 Welcome to the Colgate Intern Database

%h2 Search Your Desired Experience 

= form_tag(admin_path, :method => :get) do
  = label :experience, :industry,"Industry"
  = select :experience,:industry, ["", "The Arts/Design", "Business Services", "Communications/Media", "Consulting", "Computing/Technology", "Education", "Entertainment/Film/TV", "Environmental/Energy", "Financial Services", "Government/Public Service", "Healthcare", "Law/Legal", "Non-profit/Advocacy", "Sports/Leisure", "Scientific Research"]
  = label :experience, :season, "Season"
  = select :experience, :season, ["","Spring", "Winter", "Summer","Fall"]
  = label :experience, :organizaion, "Organization"
  = text_field :experience, 'organization'
  %br
  = label :experience, :city, "City"
  = text_field :experience, 'city'
  = label :experience, :state, "State"
  = text_field :experience, 'state'
  %br
  = submit_tag "Search"
  
%h3 Reviews:

%table#experiences
  %thead
    %tr
      %th=link_to 'Company', admin_path(:sort => 'company', :experience => @search), :id => 'company_header'
      %th=link_to 'Industry', admin_path(:sort => 'industry', :experience => @search), :id => 'industry_header'
      %th=link_to 'Role', admin_path(:sort => 'role', :experience => @search), :id => 'role_header'
      %th=link_to 'Location', admin_path(:sort => 'location', :experience => @search), :id => 'location_header'
      %th=link_to 'Date of Internship', admin_path(:sort => 'internship_date', :experience => @search), :id => 'internship_date_header'
      %th=link_to 'Date of Review', admin_path(:sort => 'review_date', :experience => @search), :id => 'review_date_header'
      %th=link_to 'Repeat?', admin_path(:sort => 'repeat', :experience => @search), :id => 'repeat_header'
      %th=link_to 'Composite Rating', admin_path(:sort => 'composite', :experience => @search), :id => 'composite_header'
      %th=link_to 'Work Relevancy', admin_path(:sort => 'hands_on_rating', :experience => @search), :id => 'hands_on_rating_header'
      %th=link_to 'Networking', admin_path(:sort => 'network_rating', :experience => @search), :id => 'network_rating_header'
      %th=link_to 'Exposure', admin_path(:sort => 'exposure_rating', :experience => @search), :id => 'exposure_rating_header'
      %th View
  %tbody
    - @experiences.each do |ex|
      %tr
        %td= link_to ex.organization, "/experiences/company/#{ex.id}"
        %td= ex.industry
        %td= ex.function
        %td= ex.citystate
        %td= ex.date_str
        %td= ex.updated_at.to_date
        %td= ex.repeat?
        %td= ex.composite.round(2)
        %td= ex.hands_on_rating
        %td= ex.network_rating
        %td= ex.exposure_rating
        %td= link_to "View", "/admin/#{ex.id}"

      
= link_to 'Share your experience', new_experience_path

= link_to 'Pending Posts', admin_unapproved_path

= link_to 'Denied Posts', "/admin/denied"

app/views/admin/show.html.haml
%h2 Colgate InternDB

%h2 Details: 


%strong.origanization= @experience.organization
%span.industry= @experience.industry
%span.date= @experience.date_str
%br
%span.function= @experience.function
%span.location= @experience.citystate
%br
%span.paid= @experience.paid_str
%span.result= @experience.result
%br
%span Contact: 
%span.contact= @experience.contact
%span.relation= @experience.contact_relation
%br
%body 
  %h3 Ratings:
  %br
  %table#rate
    %thead
      %tr
        %th Average
        %th Relevancy of Work
        %th Networking
        %th Exposure to Industry
    %tbody
      %tr
        %td= @experience.composite.round(2)
        %td= @experience.hands_on_rating
        %td= @experience.network_rating
        %td= @experience.exposure_rating    
%br
%body 
  %h3 Review:
  %br
  %h4.rprompt Would you repeat this experience?  
  %span.repeat= @experience.repeat?
  %br
  %h4 How relevant was the work?
  %p.handson= @experience.hands_on_review
  %h4 How would you describe the networking oppurtunities available?
  %p.handson= @experience.network_review
  %h4 How was the exposure to the industry?
  %p.handson= @experience.exposure_review
  %h4 Additional Comments:
  %p.handson= @experience.comments
%br
%br


%body Written by:
%span= @user.name

-if @experience.approved != true
  = button_to 'Approve', @approveURI, :method => :approve, :id => "Approve", :class => "Approve"
-if @experience.denied != true
  = button_to 'Deny', @denyURI
-if @experience.denied
  = button_to 'Delete', "/admin/#{@experience.id}", :method => :delete
= button_to 'Edit', edit_admin_path(@experience.id), :method => :get
= button_to 'Back', @previous

app/views/admin/unapproved.html.haml
%h1 Colgate InternDB Pending Posts


%table#experiences
  %thead
    %tr
      %th Student
      %th Company
      %th Industry
      %th Role
      %th Date of Internship
      %th Date of Review
      %th Composite
      %th View
  %tbody
    - @unapproved.each do |un|
      %tr
        %td= un.get_name
        %td= un.organization
        %td= un.industry
        %td= un.function
        %td= un.date_str
        %td= un.updated_at
        %td= un.composite.round(2)
        %td= link_to "View", "/admin/#{un.id}"

=link_to 'Home', '/'