config/routes.rb
InternDB::Application.routes.draw do

  resources :users
  resources :experiences
  match '/experiences/company/:id' => "experiences#company", :via => :get

  root to: 'users#home'
  root :to => redirect('/experiences')

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/:provider', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy'
  match '/admin', :to => 'admin#home'
  match '/admin/denied'
  match '/admin/unapproved'
  match '/admin/:id/approve' => 'admin#approve'
  match '/admin/:id/deny' => 'admin#deny'
  resources :admin

end

app/models/experience.rb
class Experience < ActiveRecord::Base

  attr_accessible :accepted, :approved, :contact, :extended, :function, :industry, :location, :organization, :paid, :rating, :review, :season, :user_id, :year, :denied, :city, :state, :country, :hands_on_review, :hands_on_rating, :network_review, :network_rating, :exposure_review, :exposure_rating, :contact_relation, :repeat, :comments, :composite

  def get_name
    User.find(self.user_id).name
  end
  
  def repeat?
    if self.repeat
      "Yes"
    else
      "No"
    end
  end


  def date_str
    self.season + " " + (self.year).to_s
  end

  def citystate
    self.city + "," + self.state
  end

  def paid_str
    if self.paid
      "Paid"
    else
      "Unpaid"
    end
  end
  
  def result
    if self.extended
      if self.accepted
        "Accepted Offer"
      else
        "Declined Offer"
      end
    else
      "No Offer"
    end
  end

end

app/controllers/experiences_controller.rb
class ExperiencesController < UsersController

  def new
  end

  def create
      params[:experience][:user_id] = session[:user_id]
      params[:experience][:approved] = false
      params[:experience][:approved] = false
      if params[:experience][:paid] == 'Yes'
        params[:experience][:paid] = true
      end
      if params[:experience][:repeat] = 'Yes'
        params[:experience][:repeat] = true
      end
      params[:experience][:composite] = (params[:experience][:hands_on_rating].to_i + params[:experience][:network_rating].to_i + params[:experience][:exposure_rating].to_i) / 3.0 
      @experience = Experience.create!(params[:experience])
      flash[:notice]= "Your experience at #{@experience.organization} was added successfully!"
      redirect_to root_path
  end

  def index
  end

  def company
   id = params[:id]
   @review = Experience.find(id)
   @company = @review.organization
   @experiences = Experience.where("organization = ? AND approved = ?", @company, true)
   total = @experiences.length
   hands=net=expose=0.0
   industries = Hash.new(0)
   @contact = Hash.new(0)
   roles = Hash.new(0)
   repeat = 0
   @relation = Hash.new(0)
   @experiences.each do |exp|
      repeat += 1 if exp.repeat
      hands += exp.hands_on_rating
      net += exp.network_rating
      expose += exp.exposure_rating
      industries[exp.industry] += 1
      roles[exp.function] += 1
      @contact[exp.contact] += 1
      @relation[exp.contact] = exp.contact_relation
    end
    @would = "#{repeat} of #{total} reviews said they would repeat" 
    @compo = ((hands + net + expose) / (3.0*total)).round(2)
    @hands = (hands/total).round(2)
    @net = (net/total).round(2)
    @expose = (expose/total).round(2)
    @ind = (industries.keys) * ", "
    @roles = (roles.keys.sort { |a,b| roles[b] <=> roles[a] })
    @roles = (@roles.take(5)) * ", "
    @contactlist = @contact.keys.sort{ |a,b| @contact[b] <=> @contact[a] }.take(5)
  end

  def show
    id = params[:id]
    @experience = Experience.find(id)
  end


end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/company.html.haml
%h1= @company
%p= @would

%h3 Industries:

%p= @ind

%h3 Popular Departments:

%p= @roles

%h3 Average Ratings:

%table#ratings
  %thead
    %tr
      %th Composite
      %th Work Relevancy
      %th Networking
      %th Exposure to Industry
  %tbody
    %td= @compo
    %td= @hands
    %td= @net
    %td= @expose


%h3 Helpful Contacts:

%table#Contacts
  %thead
    %tr
      %th Name
      %th Relation to Colgate
      %th Times Referenced
  - @contactlist.each do |cont|
    %tr
      %td= cont
      %td= @relation[cont]
      %td= @contact[cont]


%h3 Reviews:

%table#experiences
  %thead
    %tr
      %th Industry
      %th Role
      %th Location
      %th Date of Internship
      %th Date of Review
      %th Paid
      %th Repeat?
      %th Composite Rating
      %th Work Relevancy
      %th Networking
      %th Exposure
      %th View
  %tbody
    - @experiences.each do |ex|
      %tr
        %td= ex.industry
        %td= ex.function
        %td= ex.citystate
        %td= ex.date_str
        %td= ex.updated_at.to_date
        %td= ex.paid_str
        %td= ex.repeat?
        %td= ex.composite.round(2)
        %td= ex.hands_on_rating
        %td= ex.network_rating
        %td= ex.exposure_rating
        %td= link_to "View", "/admin/#{ex.id}"

= link_to 'Home', root_path

app/views/experiences/new.html.haml
%h1 Share Your Experience!

= form_tag experiences_path do 
   = label :experience, :organization, 'Name of Organization'  
   = text_field :experience, 'organization'
   %br
   = label :experience, :city, "City"
   = text_field :experience, 'city'
   = label :experience, :state, "State"
   = text_field :experience, 'state'
   = label :experience, :country, "Country"
   = text_field :experience, 'country'
   %br
   %br
   = label :experience, :industry, "Industry"
   = select :experience, :industry, ['The Arts/Design', "Business Services", "Communications/Media", "Consulting", "Computing/Technology", "Education", "Entertainment/Film/TV", "Environment/Energy", "Financial Services", "Government/Public Service", "Healthcare", "Law/Legal", "Non-profit/Advocacy", "Sports/Leisure", "Scientific Reasearch"]
   = label :experience, :function, "In what department?"
   = text_field :experience, 'function'
   %br
   = label :experience, :season, "Season"
   = select :experience, :season, ['Spring', 'Winter','Summer','Fall']
   = label :experience, :season, "Year"
   = select :experience, :year, [2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030] 
   %br
   = label :experience, "Paid?"
   = select :experience, :paid, ['Yes','No']
   %br
   = label :experience, :hands_on_review, 'Briefly describe the type of work that you did and/or any projects you worked on:'
   %br
   = text_area :experience, 'hands_on_review'
   %br
   = label :experience, :hands_on_rating, 'Please rate how relevant the work you did was to your industry (1 for being a coffee monkey, 5 for crucial work)'
   %br
   =select :experience, :hands_on_rating, ['1','2','3','4','5']
   %br
   = label :experience, :network_review, 'Briefly describe the networking oppurtinities your experience gave you:'
   %br
   = text_area :experience, 'network_review'
   %br
   = label :experience, :network_rating, 'Please rate the networking you obtained during your experience (1 for no networking, 5 for a spiderweb\'s worth)'
   %br
   =select :experience, :network_rating, ['1','2','3','4','5']
   %br
   = label :experience, :exposure_review, 'Briefely describe how the company exposed you to the industry through presentations, speakers, and day to day work:'
   %br
   = text_area :experience, 'exposure_review'
   %br
   = label :experience, :exposure_rating, 'Please the exposure to your industry during your experience (1 being terrible, 5 being great)'
   %br
   =select :experience, :exposure_rating, ['1','2','3','4','5']
   %br
   = label :experience, :contact, "Can you please name a contact that aided you in securing this experience?"
   = text_field :experience, :contact
   %br
   = label :experience, :contact_relation, "What is the contact's relation to Colgate?"
   = select :experience, :contact_relation, ['Parent', 'Alumni', 'Faculty', 'Other', 'None']
   %br
   = label :experience, "Knowing what you know now, would you repeat the experience?"
   = select :experience, :repeat, ['Yes', 'No']
   %br
   = label :experience, :comments, "Any additional comments?"
   %br
   = text_area :experience, 'comments'
   %br
   = submit_tag "Submit" 

app/views/experiences/show.html.haml
%h2 Colgate InternDB

%h2 Details: 


%strong.origanization= @experience.organization
%span.industry= @experience.industry
%span.date= @experience.date_str
%br
%span.function= @experience.function
%span.location= @experience.citystate
%br
%span.paid= @experience.paid_str
%span.result= @experience.result
%br
%span Contact: 
%span.contact= @experience.contact
%span.relation= @experience.contact_relation
%br
%body 
  %h3 Ratings:
  %br
  %table#rate
    %thead
      %tr
        %th Average
        %th Relevancy of Work
        %th Networking
        %th Exposure to Industry
    %tbody
      %tr
        %td= @experience.composite.round(2)
        %td= @experience.hands_on_rating
        %td= @experience.network_rating
        %td= @experience.exposure_rating    
%br
%body 
  %h3 Review:
  %br
  %h4.rprompt Would you repeat this experience?  
  %span.repeat= @experience.repeat?
  %br
  %h4 How relevant was the work?
  %p.handson= @experience.hands_on_review
  %h4 How would you describe the networking oppurtunities available?
  %p.handson= @experience.network_review
  %h4 How was the exposure to the industry?
  %p.handson= @experience.exposure_review
  %h4 Additional Comments:
  %p.handson= @experience.comments
%br
%br

= button_to 'Back', root_path